.SILENT:
GOPATH = $(shell go env GOPATH)
WIRE_PATH = "$(GOPATH)/bin/wire"
export

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

.PHONY: setup
setup: ## Set up git hooks for local development
	git config core.hooksPath .githooks

# Testing
.PHONY: test test-coverage
test:
	go test -v -race -cover ./...

test-coverage:
	go test -coverprofile=coverage.out ./...
	go tool cover -html=coverage.out -o coverage.html

# Linting
.PHONY: lint
lint:
	golangci-lint run{{if eq .QueryGen "sqlc"}} && sqlfluff lint --config .sqlfluff --dialect {{.Database}} ./sqlc/{{end}}

.PHONY: fmt
fmt:
	golangci-lint fmt{{if eq .QueryGen "sqlc"}} && sqlfluff fix --config .sqlfluff --dialect {{.Database}} ./sqlc/{{end}}

.PHONY: vet
vet: ## Run go vet
	go vet ./...

{{- if .HasDatabase}}
# Database
.PHONY: migrate-create migrate-up migrate-down
migrate-create:
	migrate create -ext sql -dir {{- if eq .QueryGen "sqlc"}} sqlc/migrations {{- else }} migrations {{- end}} $(name) 

migrate-up:
	migrate -path migrations -database '${MIGRATE_DATABASE_URL}' up

migrate-down:
	migrate -path migrations -database '${MIGRATE_DATABASE_URL}' down
{{- end}}

# Code generation
{{- if .UseWire}}
.PHONY: wire-gen
wire-gen:
	rm $(PWD)/internal/infrastructure/di/wire_gen.go 2> /dev/null; $(WIRE_PATH) $(PWD)/internal/infrastructure/di/*
{{- end}}

{{- if eq .QueryGen "sqlc"}}
.PHONY: sqlc-gen
sqlc-gen:
	rm -rf $(PWD)/internal/adapter/repository/dbgen 2> /dev/null; cd sqlc && sqlc generate
{{- end}}

{{- if .HasGRPC}}
.PHONY: proto-gen
proto-gen:
	protoc --go_out=. --go-grpc_out=. api/proto/**/*.proto
{{- end}}

gen:{{if .UseWire}} wire-gen{{end}}{{if eq .QueryGen "sqlc"}} sqlc-gen{{end}}{{if .HasGRPC}} proto-gen{{end}}

{{- if .IncludeDocker}}
# Docker
.PHONY: docker-build docker-up docker-down
docker-build:
	docker build -t $(APP_NAME) .

docker-up:
	docker-compose up -d

docker-down:
	docker-compose down
{{- end}}
