// Package manifest defines nova.yaml — the per-project descriptor that tells
// `nova add` where each component type lives, plus the module path and stack.
// It lets nova scaffold components into projects NOT generated by `nova new`:
// drop a nova.yaml describing the layout and `nova add` honours it. When no
// file is present, Default() (nova's canonical Clean Architecture layout) is
// used, so nova-generated projects need no file.
package manifest

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

// FileName is the manifest filename looked up at the project root.
const FileName = "nova.yaml"

const schemaVersion = 1

// Manifest is the parsed nova.yaml (or Default() when absent).
type Manifest struct {
	Version int               `yaml:"version"`
	Module  string            `yaml:"module"` // Go module path — used for import paths
	Stack   Stack             `yaml:"stack"`
	Layout  map[string]Target `yaml:"layout"`

	// Root is the project root the manifest was loaded from — the directory
	// components are written to. Set by Load; never serialized.
	Root string `yaml:"-"`
}

// Stack records the technology choices a generated project was built with, so
// `nova add` can pick the right variant ({db} placeholder, future per-framework
// bodies). Mirrors the relevant subset of config.ProjectConfig.
type Stack struct {
	HTTPFramework string `yaml:"http_framework"`
	Database      string `yaml:"database"`
	QueryGen      string `yaml:"query_gen"`
	Cache         string `yaml:"cache"`
	DI            string `yaml:"di"`
	MessageQueue  string `yaml:"message_queue"`
}

// Target is where one component type's files go. Dir/File/Package are
// placeholder patterns expanded per generated name (see Resolve).
type Target struct {
	Dir     string `yaml:"dir"`     // e.g. "internal/usecase/{lower}"
	File    string `yaml:"file"`    // e.g. "{snake}_repository.go"; empty ⇒ generator picks names
	Package string `yaml:"package"` // optional package-name override, e.g. "{db}"
}

// Resolved is a Target with all placeholders expanded for a concrete name.
type Resolved struct {
	Dir     string
	File    string
	Package string
}

// Default returns nova's canonical layout — the single source of truth that
// matches docs/02-project-layout.md and the output of `nova new`.
func Default() *Manifest {
	return &Manifest{
		Version: schemaVersion,
		Stack: Stack{
			HTTPFramework: "fiber",
			Database:      "postgres",
			QueryGen:      "sqlc",
			Cache:         "redis",
			DI:            "wire",
			MessageQueue:  "none",
		},
		Layout: map[string]Target{
			"entity":     {Dir: "internal/domain/entity", File: "{snake}.go", Package: "entity"},
			"port":       {Dir: "internal/domain", File: "{snake}.go", Package: "domain"},
			"usecase":    {Dir: "internal/usecase/{lower}", Package: "{lower}"},
			"repository": {Dir: "internal/adapter/repository/{db}", File: "{snake}_repository.go", Package: "{db}"},
			"cache":      {Dir: "internal/adapter/repository/redis", File: "{snake}_cache.go", Package: "redis"},
			"handler":    {Dir: "internal/transport/http/v1/{lower}", Package: "{lower}"},
			"grpc":       {Dir: "internal/transport/grpc", File: "{snake}.go", Package: "grpc"},
			"worker":     {Dir: "internal/transport/worker/v1/{lower}", Package: "{lower}"},
			"publisher":  {Dir: "internal/adapter/pubsub", File: "{snake}_publisher.go", Package: "pubsub"},
			"migration":  {Dir: "sqlc/migrations"},
			"query":      {Dir: "sqlc/query", File: "{snake}.sql"},
		},
	}
}

// Load resolves the project root (nearest ancestor of dir containing go.mod,
// else dir itself), then returns Default() overlaid with any nova.yaml found
// there. Module is filled best-effort from go.mod when the file omits it.
// A missing nova.yaml is not an error — only a malformed one is.
func Load(dir string) (*Manifest, error) {
	root := findRoot(dir)

	m := Default()
	m.Root = root
	if mod := readModule(filepath.Join(root, "go.mod")); mod != "" {
		m.Module = mod
	}

	data, err := os.ReadFile(filepath.Join(root, FileName))
	if err != nil {
		// No manifest is the common case (nova-generated projects) — use defaults.
		return m, nil //nolint:nilerr // absence is intentional, defaults apply
	}

	var fileM Manifest
	if uErr := yaml.Unmarshal(data, &fileM); uErr != nil {
		return nil, fmt.Errorf("parse %s: %w", filepath.Join(root, FileName), uErr)
	}
	overlay(m, &fileM)
	return m, nil
}

// Resolve expands a component's Target for the given name. dbOverride wins over
// Stack.Database for the {db} placeholder (used by `nova add --type`). ok is
// false when the component is not declared in the layout.
func (m *Manifest) Resolve(component, name, dbOverride string) (Resolved, bool) {
	t, ok := m.Layout[component]
	if !ok {
		return Resolved{}, false
	}
	db := dbOverride
	if db == "" {
		db = m.Stack.Database
	}
	return Resolved{
		Dir:     expand(t.Dir, name, db, m.Stack.Cache),
		File:    expand(t.File, name, db, m.Stack.Cache),
		Package: expand(t.Package, name, db, m.Stack.Cache),
	}, true
}

// overlay copies non-empty fields from src onto dst (dst starts as Default()).
// Layout merges per key and per field, so a nova.yaml that sets only a dir
// keeps the default file/package for that component.
func overlay(dst, src *Manifest) {
	if src.Version != 0 {
		dst.Version = src.Version
	}
	if src.Module != "" {
		dst.Module = src.Module
	}
	overlayStack(&dst.Stack, &src.Stack)
	for key, t := range src.Layout {
		base := dst.Layout[key]
		if t.Dir != "" {
			base.Dir = t.Dir
		}
		if t.File != "" {
			base.File = t.File
		}
		if t.Package != "" {
			base.Package = t.Package
		}
		dst.Layout[key] = base
	}
}

func overlayStack(dst, src *Stack) {
	if src.HTTPFramework != "" {
		dst.HTTPFramework = src.HTTPFramework
	}
	if src.Database != "" {
		dst.Database = src.Database
	}
	if src.QueryGen != "" {
		dst.QueryGen = src.QueryGen
	}
	if src.Cache != "" {
		dst.Cache = src.Cache
	}
	if src.DI != "" {
		dst.DI = src.DI
	}
	if src.MessageQueue != "" {
		dst.MessageQueue = src.MessageQueue
	}
}

// findRoot walks up from dir to the nearest directory containing go.mod. It
// falls back to dir when none is found (e.g. not a Go project yet).
func findRoot(dir string) string {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return dir
	}
	for {
		if _, statErr := os.Stat(filepath.Join(abs, "go.mod")); statErr == nil {
			return abs
		}
		parent := filepath.Dir(abs)
		if parent == abs {
			return dir
		}
		abs = parent
	}
}

// readModule returns the module path from a go.mod file, or "" if unreadable.
func readModule(goModPath string) string {
	data, err := os.ReadFile(goModPath)
	if err != nil {
		return ""
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		if after, found := strings.CutPrefix(strings.TrimSpace(line), "module "); found {
			return strings.TrimSpace(after)
		}
	}
	return ""
}

func expand(pattern, name, db, cache string) string {
	if pattern == "" {
		return ""
	}
	return strings.NewReplacer(
		"{lower}", strings.ToLower(name),
		"{snake}", snake(name),
		"{title}", title(name),
		"{db}", db,
		"{cache}", cache,
	).Replace(pattern)
}

func title(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func snake(s string) string {
	var out []rune
	for i, r := range s {
		if unicode.IsUpper(r) && i > 0 {
			out = append(out, '_')
		}
		out = append(out, unicode.ToLower(r))
	}
	return string(out)
}
