package cmd

import (
	"errors"
	"fmt"
	"regexp"
	"slices"
	"strings"

	"github.com/spf13/cobra"

	"github.com/quyennguyenvu/nova/internal/generator"
	"github.com/quyennguyenvu/nova/internal/manifest"
	"github.com/quyennguyenvu/nova/internal/prompt"
)

const addMaxArgs = 2

// componentNameRE: the name becomes a Go identifier, a package name and a
// file name, so only letters and digits starting with a letter are safe.
var componentNameRE = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9]*$`)

func addCommand() *cobra.Command {
	var addCmd = &cobra.Command{
		Use:     "add [type] [name]",
		Aliases: []string{"generate", "gen"},
		Short:   "Add a component to an existing project",
		Long: `
Scaffold a component into an existing Clean Architecture project.

Run without arguments for an interactive menu, or pass the type and name
directly. Output paths come from a nova.yaml at the project root when present;
otherwise nova's standard layout is used — so add works in projects not
generated by nova new.

Supported types:
	worker      Message-consumer handler (Topic + Handle) + DTO
	entity      Domain entity + repository interface
	usecase     Use case (service + DTO + errors)
	repository  Repository implementation
	handler     HTTP handler
	all         entity + usecase + repository + handler

Examples:
	nova add
	nova add entity Order
	nova add handler order
	nova add repository order --type=postgres
	nova add worker order
	nova add all order`,
		Args: cobra.MaximumNArgs(addMaxArgs),
		RunE: runAdd,
	}

	addCmd.Flags().String("type", "", "Repository database engine: postgres, mysql")
	addCmd.Flags().Bool("force", false, "Overwrite feature files that already exist")

	return addCmd
}

func runAdd(cmd *cobra.Command, args []string) error {
	m, err := manifest.Load(".")
	if err != nil {
		return fmt.Errorf("load manifest: %w", err)
	}

	repoType, _ := cmd.Flags().GetString("type")
	c := prompt.Component{DB: repoType}

	if len(args) == 0 {
		if pErr := prompt.RunComponentInteractive(&c, m.Stack.Database); pErr != nil {
			return fmt.Errorf("prompt: %w", pErr)
		}
	} else {
		c.Type = args[0]
		if len(args) > 1 {
			c.Name = args[1]
		}
	}

	if vErr := validateComponent(&c, m); vErr != nil {
		return vErr
	}

	gen := generator.NewComponentGenerator(m.Root, m)
	gen.Force, _ = cmd.Flags().GetBool("force")
	return dispatchAdd(gen, &c)
}

func validateComponent(c *prompt.Component, m *manifest.Manifest) error {
	c.Type = strings.ToLower(c.Type)
	if !slices.Contains(prompt.SupportedComponents, c.Type) {
		return fmt.Errorf(
			"unknown component %q (supported: %s)",
			c.Type, strings.Join(prompt.SupportedComponents, ", "),
		)
	}
	if c.Name == "" {
		return errors.New("component name is required")
	}
	if !componentNameRE.MatchString(c.Name) {
		return fmt.Errorf(
			"component name %q must be a Go identifier (letters and digits, starting with a letter)", c.Name,
		)
	}
	if m.Module == "" {
		return errors.New(
			"cannot determine the module path: run inside a Go module (go.mod) or set `module:` in nova.yaml",
		)
	}
	if c.DB == "" {
		c.DB = m.Stack.Database
	}
	return nil
}

func dispatchAdd(gen *generator.ComponentGenerator, c *prompt.Component) error {
	switch c.Type {
	case "worker":
		return gen.GenerateWorker(c.Name)
	case "entity":
		return gen.GenerateEntity(c.Name)
	case "usecase":
		return gen.GenerateUseCase(c.Name)
	case "repository":
		return gen.GenerateRepository(c.Name, c.DB)
	case "handler":
		return gen.GenerateHandler(c.Name)
	case "all":
		return generateAll(gen, c)
	default:
		return fmt.Errorf("unknown component %q", c.Type)
	}
}

func generateAll(gen *generator.ComponentGenerator, c *prompt.Component) error {
	if err := gen.GenerateEntity(c.Name); err != nil {
		return err
	}
	if err := gen.GenerateUseCase(c.Name); err != nil {
		return err
	}
	if err := gen.GenerateRepository(c.Name, c.DB); err != nil {
		return err
	}
	return gen.GenerateHandler(c.Name)
}
