package generator

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/quyennguyenvu/nova/internal/config"
)

// postgresDBGenStub is written into the rendered postgres adapter so go vet
// can resolve sqlc symbols without a live database. Includes both the user
// table queries AND the user_audit_log queries — worker-mode renders both.
const postgresDBGenStub = `package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type DBTX any
type Queries struct{}

func New(DBTX) *Queries { return &Queries{} }

type User struct {
	ID                   int64
	Email, Name, Password string
	CreatedAt, UpdatedAt pgtype.Timestamptz
}

type CreateUserParams struct {
	Email, Name, Password string
	CreatedAt, UpdatedAt  pgtype.Timestamptz
}
type UpdateUserParams struct {
	ID   int64
	Name string
}
type ListUsersParams struct {
	Limit, Offset int32
}

func (*Queries) CreateUser(context.Context, CreateUserParams) (User, error)   { return User{}, nil }
func (*Queries) GetUserByID(context.Context, int64) (User, error)             { return User{}, nil }
func (*Queries) GetUserByEmail(context.Context, string) (User, error)         { return User{}, nil }
func (*Queries) UpdateUser(context.Context, UpdateUserParams) error           { return nil }
func (*Queries) DeleteUser(context.Context, int64) error                      { return nil }
func (*Queries) ListUsers(context.Context, ListUsersParams) ([]User, error)   { return nil, nil }

// user_audit_log
type UserAuditLog struct {
	ID         int64
	UserID     int64
	EventType  string
	Payload    []byte
	OccurredAt pgtype.Timestamptz
}
type RecordUserAuditParams struct {
	UserID     int64
	EventType  string
	Payload    []byte
	OccurredAt pgtype.Timestamptz
}

func (*Queries) RecordUserAudit(context.Context, RecordUserAuditParams) (UserAuditLog, error) {
	return UserAuditLog{}, nil
}
`

// MySQL's sqlc emits CreateUser → (int64, error) (LastInsertID) rather than
// the Postgres-style RETURNING row. RecordUserAudit follows the same shape.
const mysqlDBGenStub = `package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

type DBTX any
type Queries struct{}

func New(DBTX) *Queries { return &Queries{} }

type User struct {
	ID                   int64
	Email, Name, Password string
	CreatedAt, UpdatedAt time.Time
}

type CreateUserParams struct {
	Email, Name, Password string
	CreatedAt, UpdatedAt  time.Time
}
type UpdateUserParams struct {
	ID   int64
	Name string
}
type ListUsersParams struct {
	Limit, Offset int32
}

func (*Queries) CreateUser(context.Context, CreateUserParams) (int64, error)  { return 0, nil }
func (*Queries) GetUserByID(context.Context, int64) (User, error)             { return User{}, nil }
func (*Queries) GetUserByEmail(context.Context, string) (User, error)         { return User{}, nil }
func (*Queries) UpdateUser(context.Context, UpdateUserParams) error           { return nil }
func (*Queries) DeleteUser(context.Context, int64) error                      { return nil }
func (*Queries) ListUsers(context.Context, ListUsersParams) ([]User, error)   { return nil, nil }

// user_audit_log
type UserAuditLog struct {
	ID         int64
	UserID     int64
	EventType  string
	Payload    json.RawMessage
	OccurredAt time.Time
}
type RecordUserAuditParams struct {
	UserID     int64
	EventType  string
	Payload    json.RawMessage
	OccurredAt time.Time
}

func (*Queries) RecordUserAudit(context.Context, RecordUserAuditParams) (int64, error) { return 0, nil }
`

// wireGenStub satisfies the Initialize* symbol that wire.go declares behind
// a build tag. We don't run wire — only ensure the package compiles when
// wire_gen.go is missing.
const wireGenHTTPStub = `// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject
// +build !wireinject

package di

import "context"

func InitializeHTTPServer(_ context.Context) (*HTTPApp, func(), error) {
	return &HTTPApp{}, func() {}, nil
}
`

const wireGenWorkerStub = `// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject
// +build !wireinject

package di

import "context"

func InitializeWorker(_ context.Context) (*WorkerApp, func(), error) {
	return &WorkerApp{}, func() {}, nil
}
`

// TestGenerateMatrix ensures every transport × database (× broker for the
// worker case) combo renders to a project that at least `go vet`s. Drop a
// variant by accident and this fails. Skipped under -short because each
// combo runs `go mod tidy` + `go vet` (10–20s).
func TestGenerateMatrix(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip("skipping generator matrix in -short mode")
	}
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain unavailable")
	}

	httpFrameworks := []string{"fiber", "gin", "chi", "echo"}
	dbs := []string{"postgres", "mysql"}
	brokers := []string{"kafka", "rabbitmq"}
	// Both DI engines render their own di package: Wire emits a build-tagged
	// wire.go (skipped by `go vet`, so we stub wire_gen.go) while fx emits a
	// plain fx.go that `go vet` actually compiles. Running every combo under
	// both proves fx's runtime wiring is as complete as Wire's generated graph.
	dis := []string{"wire", "fx"}

	for _, di := range dis {
		for _, fw := range httpFrameworks {
			for _, db := range dbs {
				name := "http_" + di + "_" + fw + "_" + db
				t.Run(name, func(t *testing.T) {
					t.Parallel()
					runHTTPMatrixCase(t, fw, db, di)
				})
			}
		}
		for _, db := range dbs {
			for _, broker := range brokers {
				name := "worker_" + di + "_" + db + "_" + broker
				t.Run(name, func(t *testing.T) {
					t.Parallel()
					runWorkerMatrixCase(t, db, broker, di)
				})
			}
		}
	}
}

func runHTTPMatrixCase(t *testing.T, framework, database, di string) {
	t.Helper()
	cfg := httpMatrixConfig(framework, database, di)
	renderAndVet(t, cfg, wireGenHTTPStub)
}

func runWorkerMatrixCase(t *testing.T, database, broker, di string) {
	t.Helper()
	cfg := workerMatrixConfig(database, broker, di)
	renderAndVet(t, cfg, wireGenWorkerStub)
}

func renderAndVet(t *testing.T, cfg *config.ProjectConfig, wireStub string) {
	t.Helper()
	dir := t.TempDir()

	gen, err := New(cfg)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if genErr := gen.Generate(dir); genErr != nil {
		t.Fatalf("Generate: %v", genErr)
	}

	if cfg.QueryGen == "sqlc" {
		writeDBGenStub(t, dir, cfg.Database)
	}
	if cfg.UseWire() {
		stubPath := filepath.Join(dir, "internal/infrastructure/di/wire_gen.go")
		if writeErr := os.WriteFile(stubPath, []byte(wireStub), 0o644); writeErr != nil {
			t.Fatalf("write wire_gen stub: %v", writeErr)
		}
	}

	if tidyErr := runGo(t, dir, "mod", "tidy"); tidyErr != nil {
		t.Fatalf("go mod tidy: %v", tidyErr)
	}
	if vetErr := runGo(t, dir, "vet", "./..."); vetErr != nil {
		t.Fatalf("go vet: %v", vetErr)
	}
}

func writeDBGenStub(t *testing.T, dir, database string) {
	t.Helper()
	stubDir := filepath.Join(dir, "internal/adapter/repository", database, "dbgen")
	if err := os.MkdirAll(stubDir, 0o755); err != nil {
		t.Fatalf("mkdir dbgen: %v", err)
	}
	stub := postgresDBGenStub
	if database == "mysql" {
		stub = mysqlDBGenStub
	}
	if err := os.WriteFile(filepath.Join(stubDir, "stub.go"), []byte(stub), 0o644); err != nil {
		t.Fatalf("write dbgen stub: %v", err)
	}
}

func httpMatrixConfig(framework, database, di string) *config.ProjectConfig {
	cfg := baseMatrixConfig(database, di)
	cfg.Transport = "http"
	cfg.HTTPFramework = framework
	cfg.Cache = "redis"
	cfg.MessageQueue = "none"
	return cfg
}

func workerMatrixConfig(database, broker, di string) *config.ProjectConfig {
	cfg := baseMatrixConfig(database, di)
	cfg.Transport = "worker"
	cfg.HTTPFramework = ""
	cfg.Cache = "none"
	cfg.MessageQueue = broker
	return cfg
}

func baseMatrixConfig(database, di string) *config.ProjectConfig {
	v := runtime.Version()
	cfg := &config.ProjectConfig{
		ProjectName:   "matrixtest",
		ModuleName:    "matrixtest",
		GoVersion:     strings.TrimPrefix(v, "go"),
		Database:      database,
		DBDriver:      "pgx",
		QueryGen:      "sqlc",
		ConfigFormat:  "yaml",
		DI:            di,
		IncludeDocker: false,
		IncludeCI:     false,
	}
	if database == "mysql" {
		cfg.DBDriver = "database/sql"
	}
	return cfg
}

// TestRegistrarEmbedsSectionPrefix pins the embedded-base routing layout: the
// registrar is feature-owned (package user, beside its handler) and gets its
// Prefix() by embedding the section base v1.Prefixed rather than declaring it,
// while the prefix is defined once in the section package (v1.APIPrefix). The
// matrix proves it compiles; this pins the shape.
func TestRegistrarEmbedsSectionPrefix(t *testing.T) {
	t.Parallel()
	cfg := httpMatrixConfig("fiber", "postgres", "wire")
	dir := t.TempDir()
	gen, err := New(cfg)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if genErr := gen.Generate(dir); genErr != nil {
		t.Fatalf("Generate: %v", genErr)
	}

	reg, err := os.ReadFile(filepath.Join(dir, "internal/transport/http/v1/user/registrar.go"))
	if err != nil {
		t.Fatalf("registrar in feature package: %v", err)
	}
	regSrc := string(reg)
	for _, want := range []string{"package user", "func NewRegistrar(h *Handler", "v1.Prefixed"} {
		if !strings.Contains(regSrc, want) {
			t.Errorf("registrar.go missing %q", want)
		}
	}
	if strings.Contains(regSrc, "func (*Registrar) Prefix()") {
		t.Error("registrar should inherit Prefix() from embedded v1.Prefixed, not declare it")
	}

	// Section base: prefix declared once, Prefix() provided via the Prefixed embed.
	base, err := os.ReadFile(filepath.Join(dir, "internal/transport/http/v1/v1.go"))
	if err != nil {
		t.Fatalf("v1 base package: %v", err)
	}
	for _, want := range []string{"package v1", `APIPrefix = "/api/v1"`, "func (Prefixed) Prefix() string"} {
		if !strings.Contains(string(base), want) {
			t.Errorf("v1.go missing %q", want)
		}
	}
	// The old version-package registrar location must not exist.
	if _, statErr := os.Stat(filepath.Join(dir, "internal/transport/http/v1/registrar.go")); statErr == nil {
		t.Error("registrar.go should not exist at the v1 package root")
	}
}

// TestChiRouterGroupsSharedPrefix guards the chi-specific fix: chi.Router.Route
// panics on a duplicate mount path, so when features share a Prefix (the norm
// under the embedded v1.Prefixed base) NewRouter must group by Prefix and mount
// each once — not call Route per registrar. The matrix renders a single feature
// so it can't catch a regression here; this pins the grouping in the template.
func TestChiRouterGroupsSharedPrefix(t *testing.T) {
	t.Parallel()
	cfg := httpMatrixConfig("chi", "postgres", "wire")
	dir := t.TempDir()
	gen, err := New(cfg)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if genErr := gen.Generate(dir); genErr != nil {
		t.Fatalf("Generate: %v", genErr)
	}
	src, err := os.ReadFile(filepath.Join(dir, "internal/transport/http/router.go"))
	if err != nil {
		t.Fatalf("router.go: %v", err)
	}
	s := string(src)
	if strings.Contains(s, "router.Route(r.Prefix(), r.Register)") {
		t.Error("chi NewRouter mounts per-registrar — features sharing a Prefix will panic on duplicate Route")
	}
	for _, want := range []string{"byPrefix", "router.Route(prefix"} {
		if !strings.Contains(s, want) {
			t.Errorf("chi router.go missing prefix-grouping marker %q", want)
		}
	}
}

// TestWorkerBrokerConfigProvider guards against a regression where the worker
// variants compiled fine but `wire gen` failed because no provider extracted
// the broker sub-config from *config.Config. The wire.go file is behind the
// `wireinject` build tag, so `go vet` in the matrix test silently skips it —
// this test asserts on the rendered text directly.
//
// The current shape uses wire.FieldsOf(new(*config.Config), "<Field>") to
// project the sub-config as a value, and the broker constructor takes the
// value type. Both halves of that contract are asserted here.
func TestWorkerBrokerConfigProvider(t *testing.T) {
	t.Parallel()

	cases := []struct {
		broker        string
		fieldName     string
		ctorSymbol    string
		ctorSubConfig string
		pubsubFile    string
	}{
		{"kafka", "Kafka", "NewKafkaProducer", "cfg config.KafkaConfig", "kafka.go"},
		{"rabbitmq", "RabbitMQ", "NewRabbitMQConnection", "cfg config.RabbitMQConfig", "rabbitmq.go"},
	}

	for _, tc := range cases {
		t.Run(tc.broker, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			cfg := workerMatrixConfig("postgres", tc.broker, "wire")

			gen, err := New(cfg)
			if err != nil {
				t.Fatalf("New: %v", err)
			}
			if genErr := gen.Generate(dir); genErr != nil {
				t.Fatalf("Generate: %v", genErr)
			}

			wire := readFile(t, filepath.Join(dir, "internal/infrastructure/di/wire.go"))
			expectFieldsOf := `wire.FieldsOf(new(*config.Config), "` + tc.fieldName + `")`
			if !strings.Contains(wire, expectFieldsOf) {
				t.Fatalf(
					"wire.go infraSet missing %q — broker constructor cannot satisfy its config dep",
					expectFieldsOf,
				)
			}

			pubsub := readFile(t, filepath.Join(dir, "internal/infrastructure/pubsub", tc.pubsubFile))
			if !strings.Contains(pubsub, tc.ctorSubConfig) {
				t.Fatalf(
					"%s: expected %s to take %s (value, not pointer)",
					tc.pubsubFile,
					tc.ctorSymbol,
					tc.ctorSubConfig,
				)
			}

			provider := readFile(t, filepath.Join(dir, "internal/infrastructure/di/provider.go"))
			if strings.Contains(provider, "provideKafkaConfig") || strings.Contains(provider, "provideRabbitMQConfig") {
				t.Fatalf("provider.go contains a stale broker config helper — should be replaced by wire.FieldsOf")
			}
		})
	}
}

// TestFxDISelection asserts the fx DI engine renders fx.go (and not wire.go),
// and that fx.go exposes the same Initialize* entry point as the Wire variant
// for each transport. The app layer calls these by name regardless of DI, so a
// missing/renamed entry point silently breaks the chosen transport.
func TestFxDISelection(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name       string
		cfg        *config.ProjectConfig
		entryPoint string
	}{
		{"http", httpMatrixConfig("fiber", "postgres", "fx"), "func InitializeHTTPServer("},
		{"worker", workerMatrixConfig("postgres", "kafka", "fx"), "func InitializeWorker("},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()

			gen, err := New(tc.cfg)
			if err != nil {
				t.Fatalf("New: %v", err)
			}
			if genErr := gen.Generate(dir); genErr != nil {
				t.Fatalf("Generate: %v", genErr)
			}

			diDir := filepath.Join(dir, "internal/infrastructure/di")
			if _, statErr := os.Stat(filepath.Join(diDir, "wire.go")); !os.IsNotExist(statErr) {
				t.Fatalf("fx project rendered wire.go — wire and fx must be mutually exclusive")
			}

			fxSrc := readFile(t, filepath.Join(diDir, "fx.go"))
			if !strings.Contains(fxSrc, tc.entryPoint) {
				t.Fatalf(
					"fx.go missing entry point %q — app layer cannot boot the %s transport",
					tc.entryPoint,
					tc.name,
				)
			}
		})
	}
}

// TestNewRejectsUnsupportedDI guards the supportedDI whitelist: removed or
// typo'd DI strategies must fail fast in New() rather than render a project
// with no Initialize* functions. "manual" was removed; "" is never valid.
func TestNewRejectsUnsupportedDI(t *testing.T) {
	t.Parallel()
	for _, di := range []string{"manual", "", "spring"} {
		cfg := baseMatrixConfig("postgres", di)
		if _, err := New(cfg); err == nil {
			t.Errorf("New() with DI=%q: want error, got nil", di)
		}
	}
	for _, di := range []string{"wire", "fx"} {
		cfg := baseMatrixConfig("postgres", di)
		if _, err := New(cfg); err != nil {
			t.Errorf("New() with DI=%q: want nil, got %v", di, err)
		}
	}
}

// TestTransportLoggerPortDecoupling pins the transport→observability.Logger
// seam: transport-layer files must depend on the pkg/observability port, never
// the concrete infrastructure/logger, and the DI graph must bridge the port to
// the concrete *logger.Logger so the App bundle + infra consumers keep it.
// Neither half is caught by the matrix's `go vet` — wire.go is build-tagged
// (vet skips it) and fx resolves its graph at runtime (vet never calls Start) —
// so assert on the rendered text here.
func TestTransportLoggerPortDecoupling(t *testing.T) {
	t.Parallel()

	render := func(t *testing.T, cfg *config.ProjectConfig) string {
		t.Helper()
		dir := t.TempDir()
		gen, err := New(cfg)
		if err != nil {
			t.Fatalf("New: %v", err)
		}
		if genErr := gen.Generate(dir); genErr != nil {
			t.Fatalf("Generate: %v", genErr)
		}
		return dir
	}

	// Transport files must reference the port and not import the concrete impl.
	assertDecoupled := func(t *testing.T, dir string, files ...string) {
		t.Helper()
		for _, f := range files {
			src := readFile(t, filepath.Join(dir, f))
			if strings.Contains(src, "internal/infrastructure/logger") {
				t.Errorf("%s imports the concrete logger — transport must depend on the observability.Logger port", f)
			}
			if !strings.Contains(src, "observability.Logger") {
				t.Errorf("%s does not reference observability.Logger — logger port not wired through", f)
			}
		}
	}

	// fx matches by exact type, so the port consumers need a concrete→port
	// caster that is both defined and registered in the infra module.
	assertFxCaster := func(t *testing.T, dir string) {
		t.Helper()
		prov := readFile(t, filepath.Join(dir, "internal/infrastructure/di/fx_provider.go"))
		if !strings.Contains(prov, "func provideObservabilityLogger(l *logger.Logger) observability.Logger") {
			t.Error("fx_provider.go missing provideObservabilityLogger caster — fx transport consumers fail at runtime")
		}
		fxSrc := readFile(t, filepath.Join(dir, "internal/infrastructure/di/fx.go"))
		if !strings.Contains(fxSrc, "provideObservabilityLogger,") {
			t.Error("fx.go infraModule does not register the provideObservabilityLogger caster")
		}
	}

	httpFiles := []string{
		"internal/transport/http/router.go",
		"internal/transport/http/middleware/logging.go",
	}
	workerFiles := []string{
		"internal/transport/worker/worker.go",
		"internal/transport/worker/consumer.go",
	}

	t.Run("wire_http", func(t *testing.T) {
		t.Parallel()
		dir := render(t, httpMatrixConfig("fiber", "postgres", "wire"))
		assertDecoupled(t, dir, httpFiles...)
		wireSrc := readFile(t, filepath.Join(dir, "internal/infrastructure/di/wire.go"))
		if !strings.Contains(wireSrc, "wire.Bind(new(observability.Logger), new(*logger.Logger))") {
			t.Error("wire.go infraSet missing the observability.Logger → *logger.Logger bind")
		}
	})

	t.Run("fx_http", func(t *testing.T) {
		t.Parallel()
		dir := render(t, httpMatrixConfig("fiber", "postgres", "fx"))
		assertDecoupled(t, dir, httpFiles...)
		assertFxCaster(t, dir)
	})

	t.Run("wire_worker", func(t *testing.T) {
		t.Parallel()
		dir := render(t, workerMatrixConfig("postgres", "kafka", "wire"))
		assertDecoupled(t, dir, workerFiles...)
	})

	t.Run("fx_worker", func(t *testing.T) {
		t.Parallel()
		dir := render(t, workerMatrixConfig("postgres", "kafka", "fx"))
		assertDecoupled(t, dir, workerFiles...)
		assertFxCaster(t, dir)
	})
}

// TestRequestIDInResponseEnvelope pins the request-ID correlation contract for
// every HTTP framework: the response envelope must expose a requestId field,
// the request-ID context plumbing must live in pkg/httputil (so httpwriter can
// stamp it without importing transport/middleware — that would be an import
// cycle), the writer must populate resp.RequestID, and the RequestID middleware
// must thread the ID through httputil.WithRequestID. None of this is provable by
// the matrix's `go vet` (it compiles fine either way), so assert on the text.
func TestRequestIDInResponseEnvelope(t *testing.T) {
	t.Parallel()

	for _, fw := range []string{"fiber", "gin", "chi", "echo"} {
		t.Run(fw, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			gen, err := New(httpMatrixConfig(fw, "postgres", "wire"))
			if err != nil {
				t.Fatalf("New: %v", err)
			}
			if genErr := gen.Generate(dir); genErr != nil {
				t.Fatalf("Generate: %v", genErr)
			}
			assertRequestIDContract(t, dir)
		})
	}
}

// assertRequestIDContract checks one rendered project carries the full
// request-ID correlation seam: envelope field, httputil plumbing, writer stamp,
// and middleware wiring.
func assertRequestIDContract(t *testing.T, dir string) {
	t.Helper()

	// The envelope carries requestId, and httputil owns the plumbing.
	env := readFile(t, filepath.Join(dir, "pkg/httputil/response.go"))
	for _, want := range []string{
		"`json:\"requestId,omitempty\"`",
		`const RequestIDHeader = "X-Request-ID"`,
		"func RequestIDFrom(ctx context.Context) string",
		"func WithRequestID(ctx context.Context, id string) context.Context",
	} {
		if !strings.Contains(env, want) {
			t.Errorf("pkg/httputil/response.go missing %q", want)
		}
	}

	// The writer stamps the ID onto the envelope.
	writer := readFile(t, filepath.Join(dir, "internal/transport/http/httpwriter/writer.go"))
	if !strings.Contains(writer, "resp.RequestID =") {
		t.Error("writer.go does not stamp resp.RequestID — responses won't carry the ID")
	}

	// The middleware threads the ID via the shared httputil plumbing and no
	// longer declares a local copy (which httpwriter couldn't reach).
	rid := readFile(t, filepath.Join(dir, "internal/transport/http/middleware/requestid.go"))
	if !strings.Contains(rid, "httputil.WithRequestID(") {
		t.Error("requestid.go does not use httputil.WithRequestID")
	}
	if strings.Contains(rid, "type requestIDKey struct{}") {
		t.Error("requestid.go still declares a local request-ID key — should use pkg/httputil")
	}
}

// TestClaudeMDGenerated pins the generated CLAUDE.md: it must render for every
// transport, inherit the working principles, and carry transport-specific
// guidance (the matrix only proves the template parses; this asserts content).
func TestClaudeMDGenerated(t *testing.T) {
	t.Parallel()

	t.Run("http_wire", func(t *testing.T) {
		t.Parallel()
		src := renderClaudeMD(t, httpMatrixConfig("fiber", "postgres", "wire"))
		mustContainAll(t, src,
			"## Working principles",
			"## Architecture",
			"## Conventions",
			"matrixtest", // ModuleName threaded through
			"dependency rule",
			"`wire_gen.go`",                  // wire-specific verification loop
			"provideRegistrars",              // HTTP-specific routing guidance
			"TxManager.WithinTx",             // transaction convention (SQL project)
			"**sqlfluff** (postgres dialect", // SQL-lint convention, parameterized dialect
			"markdownlint",                   // markdown convention (always present)
			// Pins the by-design exclusions .sqlfluff encodes
			// (exclude_rules = RF04,AM04,PG01). RF02/RF06/AL03 appear too, as
			// enforced rules — not exclusions.
			"Three rules are excluded by design",
			"**PG01**",
		)
		mustNotContain(t, src, "fx module") // wire project must not leak the fx variant
	})

	// no_sql proves the transaction + SQL-lint bullets are gated out when the
	// project has no SQL backend, while the markdown convention still renders.
	t.Run("no_sql", func(t *testing.T) {
		t.Parallel()
		cfg := httpMatrixConfig("fiber", "postgres", "wire")
		cfg.Database = "none"
		cfg.QueryGen = "none"
		src := renderClaudeMD(t, cfg)
		mustContainAll(t, src, "markdownlint")                   // always present
		mustNotContain(t, src, "TxManager.WithinTx", "sqlfluff") // gated on a SQL/sqlc backend
	})

	t.Run("worker_fx", func(t *testing.T) {
		t.Parallel()
		src := renderClaudeMD(t, workerMatrixConfig("postgres", "kafka", "fx"))
		mustContainAll(t, src,
			"kafka consumer worker", // worker project type line
			"fx module",             // fx-specific verification loop
			"provideWorkerHandlers", // worker-specific DI guidance
		)
		mustNotContain(t, src, "provideRegistrars") // worker must not leak HTTP routing
	})
}

// renderClaudeMD generates a project from cfg and returns its CLAUDE.md text.
func renderClaudeMD(t *testing.T, cfg *config.ProjectConfig) string {
	t.Helper()
	dir := t.TempDir()
	gen, err := New(cfg)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if genErr := gen.Generate(dir); genErr != nil {
		t.Fatalf("Generate: %v", genErr)
	}
	return readFile(t, filepath.Join(dir, "CLAUDE.md"))
}

// mustContainAll fails the (sub)test for every substring missing from src.
func mustContainAll(t *testing.T, src string, wants ...string) {
	t.Helper()
	for _, want := range wants {
		if !strings.Contains(src, want) {
			t.Errorf("CLAUDE.md missing %q", want)
		}
	}
}

// mustNotContain fails the (sub)test for any substring that leaks into src.
func mustNotContain(t *testing.T, src string, banned ...string) {
	t.Helper()
	for _, b := range banned {
		if strings.Contains(src, b) {
			t.Errorf("CLAUDE.md unexpectedly contains %q", b)
		}
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(b)
}

func runGo(t *testing.T, dir string, args ...string) error {
	t.Helper()
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Logf("go %s output:\n%s", strings.Join(args, " "), out)
	}
	return err
}
