package generator

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"nova/internal/config"
)

// postgresDBGenStub is written into the rendered postgres adapter so go vet
// can resolve sqlc symbols without a live database. Includes both the user
// table queries AND the user_audit_log queries — worker-mode renders both.
const postgresDBGenStub = `package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type DBTX interface{}
type Queries struct{}

func New(DBTX) *Queries { return &Queries{} }

type User struct {
	ID                   int64
	Email, Name, Password string
	CreatedAt, UpdatedAt pgtype.Timestamptz
}

type CreateUserParams struct {
	Email, Name, Password string
	CreatedAt, UpdatedAt  pgtype.Timestamptz
}
type UpdateUserParams struct {
	ID   int64
	Name string
}
type ListUsersParams struct {
	Limit, Offset int32
}

func (*Queries) CreateUser(context.Context, CreateUserParams) (User, error)   { return User{}, nil }
func (*Queries) GetUserByID(context.Context, int64) (User, error)             { return User{}, nil }
func (*Queries) GetUserByEmail(context.Context, string) (User, error)         { return User{}, nil }
func (*Queries) UpdateUser(context.Context, UpdateUserParams) error           { return nil }
func (*Queries) DeleteUser(context.Context, int64) error                      { return nil }
func (*Queries) ListUsers(context.Context, ListUsersParams) ([]User, error)   { return nil, nil }

// user_audit_log
type UserAuditLog struct {
	ID         int64
	UserID     int64
	EventType  string
	Payload    []byte
	OccurredAt pgtype.Timestamptz
}
type RecordUserAuditParams struct {
	UserID     int64
	EventType  string
	Payload    []byte
	OccurredAt pgtype.Timestamptz
}

func (*Queries) RecordUserAudit(context.Context, RecordUserAuditParams) (UserAuditLog, error) {
	return UserAuditLog{}, nil
}
`

// MySQL's sqlc emits CreateUser → (int64, error) (LastInsertID) rather than
// the Postgres-style RETURNING row. RecordUserAudit follows the same shape.
const mysqlDBGenStub = `package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

type DBTX interface{}
type Queries struct{}

func New(DBTX) *Queries { return &Queries{} }

type User struct {
	ID                   int64
	Email, Name, Password string
	CreatedAt, UpdatedAt time.Time
}

type CreateUserParams struct {
	Email, Name, Password string
	CreatedAt, UpdatedAt  time.Time
}
type UpdateUserParams struct {
	ID   int64
	Name string
}
type ListUsersParams struct {
	Limit, Offset int32
}

func (*Queries) CreateUser(context.Context, CreateUserParams) (int64, error)  { return 0, nil }
func (*Queries) GetUserByID(context.Context, int64) (User, error)             { return User{}, nil }
func (*Queries) GetUserByEmail(context.Context, string) (User, error)         { return User{}, nil }
func (*Queries) UpdateUser(context.Context, UpdateUserParams) error           { return nil }
func (*Queries) DeleteUser(context.Context, int64) error                      { return nil }
func (*Queries) ListUsers(context.Context, ListUsersParams) ([]User, error)   { return nil, nil }

// user_audit_log
type UserAuditLog struct {
	ID         int64
	UserID     int64
	EventType  string
	Payload    json.RawMessage
	OccurredAt time.Time
}
type RecordUserAuditParams struct {
	UserID     int64
	EventType  string
	Payload    json.RawMessage
	OccurredAt time.Time
}

func (*Queries) RecordUserAudit(context.Context, RecordUserAuditParams) (int64, error) { return 0, nil }
`

// wireGenStub satisfies the Initialize* symbol that wire.go declares behind
// a build tag. We don't run wire — only ensure the package compiles when
// wire_gen.go is missing.
const wireGenHTTPStub = `// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject
// +build !wireinject

package di

import "context"

func InitializeHTTPServer(_ context.Context) (*HTTPApp, func(), error) {
	return &HTTPApp{}, func() {}, nil
}
`

const wireGenWorkerStub = `// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject
// +build !wireinject

package di

import "context"

func InitializeWorker(_ context.Context) (*WorkerApp, func(), error) {
	return &WorkerApp{}, func() {}, nil
}
`

// TestGenerateMatrix ensures every transport × database (× broker for the
// worker case) combo renders to a project that at least `go vet`s. Drop a
// variant by accident and this fails. Skipped under -short because each
// combo runs `go mod tidy` + `go vet` (10–20s).
func TestGenerateMatrix(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip("skipping generator matrix in -short mode")
	}
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain unavailable")
	}

	httpFrameworks := []string{"fiber", "gin", "chi", "echo"}
	dbs := []string{"postgres", "mysql"}
	brokers := []string{"kafka", "rabbitmq"}

	for _, fw := range httpFrameworks {
		for _, db := range dbs {
			name := "http_" + fw + "_" + db
			t.Run(name, func(t *testing.T) {
				t.Parallel()
				runHTTPMatrixCase(t, fw, db)
			})
		}
	}
	for _, db := range dbs {
		for _, broker := range brokers {
			name := "worker_" + db + "_" + broker
			t.Run(name, func(t *testing.T) {
				t.Parallel()
				runWorkerMatrixCase(t, db, broker)
			})
		}
	}
}

func runHTTPMatrixCase(t *testing.T, framework, database string) {
	t.Helper()
	cfg := httpMatrixConfig(framework, database)
	renderAndVet(t, cfg, wireGenHTTPStub)
}

func runWorkerMatrixCase(t *testing.T, database, broker string) {
	t.Helper()
	cfg := workerMatrixConfig(database, broker)
	renderAndVet(t, cfg, wireGenWorkerStub)
}

func renderAndVet(t *testing.T, cfg *config.ProjectConfig, wireStub string) {
	t.Helper()
	dir := t.TempDir()

	gen, err := New(cfg)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if genErr := gen.Generate(dir); genErr != nil {
		t.Fatalf("Generate: %v", genErr)
	}

	if cfg.QueryGen == "sqlc" {
		writeDBGenStub(t, dir, cfg.Database)
	}
	if cfg.UseWire() {
		stubPath := filepath.Join(dir, "internal/infrastructure/di/wire_gen.go")
		if writeErr := os.WriteFile(stubPath, []byte(wireStub), 0o644); writeErr != nil {
			t.Fatalf("write wire_gen stub: %v", writeErr)
		}
	}

	if tidyErr := runGo(t, dir, "mod", "tidy"); tidyErr != nil {
		t.Fatalf("go mod tidy: %v", tidyErr)
	}
	if vetErr := runGo(t, dir, "vet", "./..."); vetErr != nil {
		t.Fatalf("go vet: %v", vetErr)
	}
}

func writeDBGenStub(t *testing.T, dir, database string) {
	t.Helper()
	stubDir := filepath.Join(dir, "internal/adapter/repository", database, "dbgen")
	if err := os.MkdirAll(stubDir, 0o755); err != nil {
		t.Fatalf("mkdir dbgen: %v", err)
	}
	stub := postgresDBGenStub
	if database == "mysql" {
		stub = mysqlDBGenStub
	}
	if err := os.WriteFile(filepath.Join(stubDir, "stub.go"), []byte(stub), 0o644); err != nil {
		t.Fatalf("write dbgen stub: %v", err)
	}
}

func httpMatrixConfig(framework, database string) *config.ProjectConfig {
	cfg := baseMatrixConfig(database)
	cfg.Transport = "http"
	cfg.HTTPFramework = framework
	cfg.Cache = "redis"
	cfg.MessageQueue = "none"
	return cfg
}

func workerMatrixConfig(database, broker string) *config.ProjectConfig {
	cfg := baseMatrixConfig(database)
	cfg.Transport = "worker"
	cfg.HTTPFramework = ""
	cfg.Cache = "none"
	cfg.MessageQueue = broker
	return cfg
}

func baseMatrixConfig(database string) *config.ProjectConfig {
	v := runtime.Version()
	cfg := &config.ProjectConfig{
		ProjectName:   "matrixtest",
		ModuleName:    "matrixtest",
		GoVersion:     strings.TrimPrefix(v, "go"),
		Database:      database,
		DBDriver:      "pgx",
		QueryGen:      "sqlc",
		ConfigFormat:  "yaml",
		DI:            "wire",
		IncludeDocker: false,
		IncludeCI:     false,
	}
	if database == "mysql" {
		cfg.DBDriver = "database/sql"
	}
	return cfg
}

func runGo(t *testing.T, dir string, args ...string) error {
	t.Helper()
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Logf("go %s output:\n%s", strings.Join(args, " "), out)
	}
	return err
}
