package generator

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"nova/internal/config"
)

// dbgenStub is written into the rendered postgres adapter so go vet can resolve
// sqlc symbols without a live database. The real dbgen package comes from
// `sqlc generate`; this stub only needs to satisfy the compiler.
const postgresDBGenStub = `package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type DBTX interface{}
type Queries struct{}

func New(DBTX) *Queries { return &Queries{} }

type User struct {
	ID                   int64
	Email, Name, Password string
	CreatedAt, UpdatedAt pgtype.Timestamptz
}

type CreateUserParams struct {
	Email, Name, Password string
	CreatedAt, UpdatedAt  pgtype.Timestamptz
}
type UpdateUserParams struct {
	ID   int64
	Name string
}
type ListUsersParams struct {
	Limit, Offset int32
}

func (*Queries) CreateUser(context.Context, CreateUserParams) (User, error)   { return User{}, nil }
func (*Queries) GetUserByID(context.Context, int64) (User, error)             { return User{}, nil }
func (*Queries) GetUserByEmail(context.Context, string) (User, error)         { return User{}, nil }
func (*Queries) UpdateUser(context.Context, UpdateUserParams) error           { return nil }
func (*Queries) DeleteUser(context.Context, int64) error                      { return nil }
func (*Queries) ListUsers(context.Context, ListUsersParams) ([]User, error)   { return nil, nil }
`

// MySQL's sqlc emits CreateUser → (int64, error) (LastInsertID) rather than
// the Postgres-style RETURNING row. The stub must match that signature or
// vet fails on the repo's `user.ID = id` assignment.
const mysqlDBGenStub = `package dbgen

import (
	"context"
	"time"
)

type DBTX interface{}
type Queries struct{}

func New(DBTX) *Queries { return &Queries{} }

type User struct {
	ID                   int64
	Email, Name, Password string
	CreatedAt, UpdatedAt time.Time
}

type CreateUserParams struct {
	Email, Name, Password string
	CreatedAt, UpdatedAt  time.Time
}
type UpdateUserParams struct {
	ID   int64
	Name string
}
type ListUsersParams struct {
	Limit, Offset int32
}

func (*Queries) CreateUser(context.Context, CreateUserParams) (int64, error)  { return 0, nil }
func (*Queries) GetUserByID(context.Context, int64) (User, error)             { return User{}, nil }
func (*Queries) GetUserByEmail(context.Context, string) (User, error)         { return User{}, nil }
func (*Queries) UpdateUser(context.Context, UpdateUserParams) error           { return nil }
func (*Queries) DeleteUser(context.Context, int64) error                      { return nil }
func (*Queries) ListUsers(context.Context, ListUsersParams) ([]User, error)   { return nil, nil }
`

// wireGenStub satisfies the InitializeHTTPServer symbol that wire.go declares
// behind a build tag. We don't actually run wire — only ensure the package
// compiles when wire_gen.go is missing. Returning a zero-value HTTPApp is
// acceptable for compile-only verification.
const wireGenStub = `// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject
// +build !wireinject

package di

import "context"

func InitializeHTTPServer(_ context.Context) (*HTTPApp, func(), error) {
	return &HTTPApp{}, func() {}, nil
}
`

// TestGenerateMatrix ensures every framework × database combo renders to a
// project that at least `go vet`s. Drop a variant by accident and this
// fails. Skipped under -short because each combo runs `go mod tidy` +
// `go vet` (10–20s).
func TestGenerateMatrix(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip("skipping generator matrix in -short mode")
	}
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain unavailable")
	}

	frameworks := []string{"fiber", "gin", "chi", "echo"}
	dbs := []string{"postgres", "mysql"}

	for _, fw := range frameworks {
		for _, db := range dbs {
			name := fw + "_" + db
			t.Run(name, func(t *testing.T) {
				t.Parallel()
				runOneMatrixCase(t, fw, db)
			})
		}
	}
}

// runOneMatrixCase renders one (framework, db) tuple and verifies it compiles.
// Split out from TestGenerateMatrix so gocognit doesn't trip on nested loops.
func runOneMatrixCase(t *testing.T, framework, database string) {
	t.Helper()

	cfg := matrixConfig(framework, database)
	dir := t.TempDir()

	gen, err := New(cfg)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if genErr := gen.Generate(dir); genErr != nil {
		t.Fatalf("Generate: %v", genErr)
	}

	if cfg.QueryGen == "sqlc" {
		writeDBGenStub(t, dir, database)
	}
	if cfg.UseWire() {
		stubPath := filepath.Join(dir, "internal/infrastructure/di/wire_gen.go")
		if writeErr := os.WriteFile(stubPath, []byte(wireGenStub), 0o644); writeErr != nil {
			t.Fatalf("write wire_gen stub: %v", writeErr)
		}
	}

	if tidyErr := runGo(t, dir, "mod", "tidy"); tidyErr != nil {
		t.Fatalf("go mod tidy: %v", tidyErr)
	}
	if vetErr := runGo(t, dir, "vet", "./..."); vetErr != nil {
		t.Fatalf("go vet: %v", vetErr)
	}
}

func writeDBGenStub(t *testing.T, dir, database string) {
	t.Helper()
	stubDir := filepath.Join(dir, "internal/adapter/repository", database, "dbgen")
	if err := os.MkdirAll(stubDir, 0o755); err != nil {
		t.Fatalf("mkdir dbgen: %v", err)
	}
	stub := postgresDBGenStub
	if database == "mysql" {
		stub = mysqlDBGenStub
	}
	if err := os.WriteFile(filepath.Join(stubDir, "stub.go"), []byte(stub), 0o644); err != nil {
		t.Fatalf("write dbgen stub: %v", err)
	}
}

func matrixConfig(framework, database string) *config.ProjectConfig {
	v := runtime.Version()
	cfg := &config.ProjectConfig{
		ProjectName:   "matrixtest",
		ModuleName:    "matrixtest",
		GoVersion:     strings.TrimPrefix(v, "go"),
		Transport:     "http",
		HTTPFramework: framework,
		Database:      database,
		DBDriver:      "pgx",
		QueryGen:      "sqlc",
		Cache:         "redis",
		MessageQueue:  "none",
		ConfigFormat:  "yaml",
		DI:            "wire",
		IncludeDocker: false,
		IncludeCI:     false,
	}
	if database == "mysql" {
		cfg.DBDriver = "database/sql"
	}
	return cfg
}

func runGo(t *testing.T, dir string, args ...string) error {
	t.Helper()
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Logf("go %s output:\n%s", strings.Join(args, " "), out)
	}
	return err
}
